[workspace]

members = [
    "packages/qwik/src/napi",
    "packages/qwik/src/wasm",
    "packages/qwik/src/optimizer/core",
]
exclude = ["packages/qwik/src/wasm"]
resolver = "2"

[profile.release]
debug = 0
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"

