[workspace]

members = [
    "packages/qwik/src/napi",
    "packages/qwik/src/wasm",
    "packages/qwik/src/optimizer/cli",
    "packages/qwik/src/optimizer/core",
]
exclude = ["packages/qwik/src/wasm"]
resolver = "2"

[profile.release]
debug = 0

