[package]
authors = ["Manu <manu@builder.io>"]
name = "qwik-wasm"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/QwikDev/qwik"
license = "MIT"
description = "Qwik optimizer compiler"
keywords = ["qwik", "swc", "javascript", "optimizer", "compiler"]
categories = ["development-tools", "development-tools::cargo-plugins"]

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3"
qwik-core = { path = "../optimizer/core" }
serde = "1"
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
parking_lot_core = "=0.9"
console_error_panic_hook = { version = "0.1", optional = true }
getrandom = { version = "0.2", features = ["js"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile.release]
debug = 0
lto=true
codegen-units=1
opt-level="z"
panic="abort"
