[package]
authors = ["Manu Mtz.-Almeida <manu@builder.io>"]
name = "qwik_napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
napi = { version = "2", features = ["serde-json", "tokio_rt"] }
napi-derive = "2"
qwik-core = { path = "../optimizer/core" }

[target.'cfg(windows)'.dependencies]
mimalloc = { version = "0.1.25", default-features = false }

[build-dependencies]
napi-build = { version = "2" }
