[package]
authors = ["Manu <manu@builder.io>"]
name = "qwik-core"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/QwikDev/qwik"
license = "MIT"
description = "Qwik optimizer compiler"
keywords = ["qwik", "swc", "javascript", "optimizer", "compiler"]
categories = ["development-tools", "development-tools::cargo-plugins"]

[lib]
crate-type = ["rlib"]

[dependencies]
swc_ecmascript = { version = "*", features = ["codegen", "utils", "visit", "parser", "transforms", "typescript",  "react", "optimization"] }
swc_common = { version = "*", features = ["sourcemap"] }
swc_atoms = "*"
serde = "1.0.160"
serde_bytes = "0.11.9"
serde_json = "1.0.96"
simple-error = "0.3.0"
base64 = "0.22.1"
pathdiff = "0.2.1"
relative-path = "1.8.0"
lazy_static = "1.4.0"
anyhow = "1.0.70"
derivative = "2.2.0"
rayon = "1.7.0"
path-slash="0.2.1"

[dev-dependencies]
insta = "1.29.0"

[features]
fs=[]
parallel=[]
